// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace DiskInfoLibWinRT
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        
        String Firmware{ get; };
        Int32 DriveNum{ get; };
        Double DiskStatus{ get; };
        String AtaAtapi{ get; };
        String BufferSize{ get; };
        String Feature{ get; };
        String FirmwareRev{ get; };
        String DriveMap{ get; };
    }
}
