import "AtaSmartInfo.idl";

namespace DiskInfoLibWinRT
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        Windows.Foundation.Collections.IVector<DiskInfoLibWinRT.AtaSmartInfo> Info{ get; };

        void UpdateAll();
        void SaveText(String fileName); //CDiskInfoDlg::SaveText()

        Boolean AsciiView;
        Boolean DumpSmartReadData;
        Boolean DumpSmartReadThreshold;
        Boolean DumpIdentifyDevice;
    }
}
