namespace DiskInfoLibWinRT
{
    [bindable]
    [default_interface]
    runtimeclass GraphDataPoint 
    {
        GraphDataPoint(UInt64 xValue, UInt32 yValue);
        Windows.Foundation.DateTime XValue;
        UInt32 YValue;
    }
}
